import re
import pandas as pd
import numpy as np

EP_PATH = "episode_metrics_by_hand.csv"   # file generated by latency_etl.py
ep = pd.read_csv(EP_PATH)

# ---------- 1) filename parsing ----------
def parse_filename(name: str):
    # TD13-M3_A5R4..
    m = re.search(r"(TD\d+)-M(\d+)(?:_A(\d+))?", name)
    if not m:
        return pd.Series([np.nan, np.nan, np.nan])
    subject = m.group(1)
    month = int(m.group(2))
    session = int(m.group(3)) if m.group(3) else 1
    return pd.Series([subject, month, session])


ep[["subject", "month", "session"]] = ep["source_file"].apply(parse_filename)

# ---------- 2) subject-level table ----------
def iqr(series):
    q1 = series.quantile(0.25)
    q3 = series.quantile(0.75)
    return q3 - q1


subj = ep.groupby("subject").agg(
    n_episodes=("episode_idx", "count"),

    # response rate (any-hand)
    response_rate=("any_responded", "mean"),

    # latency (any-hand)
    mean_latency_ms=("any_latency_to_first_reach_ms", "mean"),
    std_latency_ms=("any_latency_to_first_reach_ms", "std"),
    median_latency_ms=("any_latency_to_first_reach_ms", "median"),
    iqr_latency_ms=("any_latency_to_first_reach_ms", iqr),

    # hand response rates (episode-level proportions within subject)
    la_rate=("la_responded", "mean"),
    ra_rate=("ra_responded", "mean"),

    # counts for attempts/successes (sum across episodes)
    la_attempts=("la_reach_onset_count", "sum"),
    ra_attempts=("ra_reach_onset_count", "sum"),
    la_success=("la_success_onset_count", "sum"),
    ra_success=("ra_success_onset_count", "sum"),
).reset_index()

subj["total_attempts"] = subj["la_attempts"] + subj["ra_attempts"]
subj["total_success"] = subj["la_success"] + subj["ra_success"]
subj["success_rate"] = subj["total_success"] / subj["total_attempts"]

# hand bias index: (RA-LA)/(RA+LA)
subj["hand_bias"] = (subj["ra_rate"] - subj["la_rate"]) / (subj["ra_rate"] + subj["la_rate"])

print("\n=== SUBJECT-LEVEL SUMMARY ===")
print(subj.sort_values("subject").to_string(index=False))

# ---------- 3) latency vs success correlation (subject-level) ----------
corr = subj[["mean_latency_ms", "success_rate"]].corr().iloc[0, 1]
print(f"\nSubject-level corr(mean_latency_ms, success_rate) = {corr:.3f}")

# ---------- 4) bimanual reaching rate (episode-level) ----------
ep["bimanual"] = ((ep["la_responded"] == 1) & (ep["ra_responded"] == 1)).astype(int)
bimanual_rate = ep["bimanual"].mean()
print(f"\nEpisode-level bimanual rate = {bimanual_rate:.3f}")

# ---------- 5) month-level descriptive stats (not inferential; just describe) ----------
month_stats = ep.groupby("month").agg(
    n_episodes=("episode_idx", "count"),
    response_rate=("any_responded", "mean"),
    mean_latency_ms=("any_latency_to_first_reach_ms", "mean"),
    std_latency_ms=("any_latency_to_first_reach_ms", "std"),
    median_latency_ms=("any_latency_to_first_reach_ms", "median"),
    iqr_latency_ms=("any_latency_to_first_reach_ms", iqr),
    # attempts/success across both hands
    total_attempts=("la_reach_onset_count", "sum"),
    total_success=("la_success_onset_count", "sum"),
).reset_index()

month_stats = ep.groupby("month").apply(
    lambda g: pd.Series({
        "n_episodes": int(len(g)),
        "response_rate": float(g["any_responded"].mean()),
        "mean_latency_ms": float(pd.to_numeric(g["any_latency_to_first_reach_ms"], errors="coerce").mean()),
        "std_latency_ms": float(pd.to_numeric(g["any_latency_to_first_reach_ms"], errors="coerce").std()),
        "median_latency_ms": float(pd.to_numeric(g["any_latency_to_first_reach_ms"], errors="coerce").median()),
        "iqr_latency_ms": float(iqr(pd.to_numeric(g["any_latency_to_first_reach_ms"], errors="coerce"))),
        "total_attempts": int(g["la_reach_onset_count"].fillna(0).sum() + g["ra_reach_onset_count"].fillna(0).sum()),
        "total_success": int(g["la_success_onset_count"].fillna(0).sum() + g["ra_success_onset_count"].fillna(0).sum()),
    })
).reset_index()

month_stats["success_rate"] = month_stats["total_success"] / month_stats["total_attempts"]

print("\n=== MONTH-LEVEL DESCRIPTIVES ===")
print(month_stats.sort_values("month").to_string(index=False))

# ---------- 6) save tables ----------
subj.to_csv("subject_level_summary.csv", index=False)
month_stats.to_csv("month_level_summary.csv", index=False)
print("\nWrote: subject_level_summary.csv, month_level_summary.csv")
